-- 010_stylex_latex_colours.sql
-- Generated by _inbox/generate_stylex_migration.py from the scraped
-- Stylex Balloons colour list at https://stylexballoons.com.au/pages/colous
-- (50 colours, all 5-inch latex). Don't hand-edit this file — re-run
-- the generator if the colour list changes upstream.
--
-- What this migration does:
--   1. Adds a `photo_url` column to inventory_items
--   2. Archives the previous 20 ad-hoc latex colour SKUs (kept the mixed
--      `balloon-latex-5in-pack` for recipe compatibility)
--   3. Inserts 50 fresh SKUs matching Stylex's catalogue, each with
--      photo_url + Stylex supplier source pointing at the specific
--      product collection page
--   4. Adds Hayden Agencies + Online Party Supplies as backup sources
--      (no URLs — Jade fills in over time)

-- 1. Add photo_url column. Idempotent-safe via column-not-exists check
--    pattern: SQLite doesn't support IF NOT EXISTS on ALTER TABLE so we
--    let it raise on a re-run; the migration runner only applies each
--    version once anyway.
ALTER TABLE inventory_items ADD COLUMN photo_url TEXT;

-- 2. Archive the previous 20 hand-rolled colour rows (preserves history;
--    Jade can restore via the Show-archived toggle if needed). The mixed
--    pack stays because recipes still reference its sku.
UPDATE inventory_items
   SET archived = 1, updated_at = datetime('now')
 WHERE category = 'Balloons - Latex'
   AND sku != 'balloon-latex-5in-pack'
   AND sku != 'balloon-latex-5in-stylex-pack';

-- 3. Insert all 50 Stylex colours with photo + product page URLs.
INSERT OR IGNORE INTO inventory_items (sku, name, category, unit, on_hand, reorder_at, photo_url, notes) VALUES
  ('balloon-latex-5in-stylex-avocado-green', '5-inch latex — Avocado Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_avocado.png?v=1699447406&width=200', ''),
  ('balloon-latex-5in-stylex-baby-blue', '5-inch latex — Baby Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_baby_blue.png?v=1699447435&width=200', ''),
  ('balloon-latex-5in-stylex-baby-pink', '5-inch latex — Baby Pink', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_baby_pink.png?v=1699447442&width=200', ''),
  ('balloon-latex-5in-stylex-berry', '5-inch latex — Berry', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_berry.png?v=1699447449&width=200', ''),
  ('balloon-latex-5in-stylex-black', '5-inch latex — Black', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_black.png?v=1699447457&width=200', ''),
  ('balloon-latex-5in-stylex-blush', '5-inch latex — Blush', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_blush.png?v=1699449073&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-bronze-gold', '5-inch latex — Chrome Bronze Gold', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_bronze_chrome.png?v=1706331140&width=200', ''),
  ('balloon-latex-5in-stylex-burnt-orange', '5-inch latex — Burnt Orange', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_burnt_orange.png?v=1699449081&width=200', ''),
  ('balloon-latex-5in-stylex-caribbean-blue', '5-inch latex — Caribbean Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_caribbean.png?v=1699449089&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-blue', '5-inch latex — Chrome Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/chrome_blue_12inch.png?v=1730192728&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-champagne', '5-inch latex — Chrome Champagne', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/chrome_champagne_5_inch.png?v=1730194818&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-green', '5-inch latex — Chrome Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/chrome_green_5_inch.png?v=1730194065&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-gold-yellow', '5-inch latex — Chrome Gold Yellow', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_chrome_yellow.png?v=1699450935&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-purple', '5-inch latex — Chrome Purple', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/05aaadee-848d-484c-809d-52deb4d4383a.jpg?v=1730193451&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-rose-gold', '5-inch latex — Chrome Rose Gold', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_rose_gold.png?v=1699450947&width=200', ''),
  ('balloon-latex-5in-stylex-chrome-silver', '5-inch latex — Chrome Silver', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_silver_chrome.png?v=1699450958&width=200', ''),
  ('balloon-latex-5in-stylex-coffee', '5-inch latex — Coffee', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_coffee.png?v=1699449097&width=200', ''),
  ('balloon-latex-5in-stylex-dark-blue', '5-inch latex — Dark Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_dark_blue.png?v=1699449105&width=200', ''),
  ('balloon-latex-5in-stylex-golden-rod-yellow', '5-inch latex — Golden Rod Yellow', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_goldenrod.png?v=1699449113&width=200', ''),
  ('balloon-latex-5in-stylex-fashion-red', '5-inch latex — Fashion Red', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/1_794fb1b2-772b-477b-bbf0-5f73a178d885.png?v=1730101593&width=200', ''),
  ('balloon-latex-5in-stylex-grey', '5-inch latex — Grey', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_grey.png?v=1699449120&width=200', ''),
  ('balloon-latex-5in-stylex-hot-purple', '5-inch latex — Hot Purple', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_plum.png?v=1699449127&width=200', ''),
  ('balloon-latex-5in-stylex-hunter-green', '5-inch latex — Hunter Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_hunter_green.png?v=1699449136&width=200', ''),
  ('balloon-latex-5in-stylex-lavender', '5-inch latex — Lavender', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_lavender.png?v=1699449144&width=200', ''),
  ('balloon-latex-5in-stylex-light-blue', '5-inch latex — Light Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_light_blue.png?v=1699449151&width=200', ''),
  ('balloon-latex-5in-stylex-lime-green', '5-inch latex — Lime Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inchlimenew.png?v=1709948515&width=200', ''),
  ('balloon-latex-5in-stylex-matcha-green', '5-inch latex — Matcha Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_matcha.png?v=1699449158&width=200', ''),
  ('balloon-latex-5in-stylex-mid-blue', '5-inch latex — Mid Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_midblue.png?v=1699449166&width=200', ''),
  ('balloon-latex-5in-stylex-mint-green', '5-inch latex — Mint Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_mintgreen.png?v=1699449172&width=200', ''),
  ('balloon-latex-5in-stylex-navy', '5-inch latex — Navy', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_navy.png?v=1699449180&width=200', ''),
  ('balloon-latex-5in-stylex-orange', '5-inch latex — Orange', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_orange.png?v=1699450967&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-dusk-blue', '5-inch latex — Pastel Dusk Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/files/pastelduskblue5inchupdated.png?v=1705404729&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-dusk-cream', '5-inch latex — Pastel Dusk Cream', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/pastelcream5inchupdated_1a82068f-8350-4b15-b08c-a688cf78abeb.png?v=1730113102&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-dusk-laurel-green', '5-inch latex — Pastel Dusk Laurel Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/files/pasteldusklaurelgreen5inchupdated.png?v=1705404797&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-dusk-lavender', '5-inch latex — Pastel Dusk Lavender', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/pasteldusklavender5inchupdated.png?v=1730113132&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-dusk-rose', '5-inch latex — Pastel Dusk Rose', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/files/pastelduskrose5inchupdated.png?v=1705404836&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-blue', '5-inch latex — Pastel Blue', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pastelblue.png?v=1699450976&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-green', '5-inch latex — Pastel Green', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pastelgreen.png?v=1699450983&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-lilac', '5-inch latex — Pastel Lilac', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pastel_lilac.png?v=1699450990&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-pink', '5-inch latex — Pastel Pink', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pastelpink.png?v=1699450995&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-light-yellow', '5-inch latex — Pastel Light Yellow', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/2_5e564017-65fb-4dc5-814a-dcbeacbc7a4c.png?v=1730112889&width=200', ''),
  ('balloon-latex-5in-stylex-pastel-yellow', '5-inch latex — Pastel Yellow', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pastel_yellow.png?v=1699451001&width=200', ''),
  ('balloon-latex-5in-stylex-pearl-white', '5-inch latex — Pearl White', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_pearl_white.png?v=1699451008&width=200', ''),
  ('balloon-latex-5in-stylex-red', '5-inch latex — Red', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_red.png?v=1699451017&width=200', ''),
  ('balloon-latex-5in-stylex-rose-pink', '5-inch latex — Rose Pink', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_rosepink.png?v=1699451025&width=200', ''),
  ('balloon-latex-5in-stylex-rosewood', '5-inch latex — Rosewood', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_rosewood.png?v=1699451032&width=200', ''),
  ('balloon-latex-5in-stylex-spring-lilac', '5-inch latex — Spring Lilac', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_spring_lilac.png?v=1699451043&width=200', ''),
  ('balloon-latex-5in-stylex-white', '5-inch latex — White', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/white.jpg?v=1699445642&width=200', ''),
  ('balloon-latex-5in-stylex-white-sand', '5-inch latex — White Sand', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/white_sand.png?v=1699445622&width=200', ''),
  ('balloon-latex-5in-stylex-yellow', '5-inch latex — Yellow', 'Balloons - Latex', 'pack', 0, 2, 'https://stylexballoons.com.au/cdn/shop/collections/5inch_yellow.png?v=1699451255&width=200', '');

-- 4. Stylex supplier source for each new SKU — preferred, with the
--    specific product page URL filled in. Idempotent via NOT EXISTS.
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/avocado-green', 1, 'Stylex catalogue page for Avocado Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-avocado-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/baby-blue', 1, 'Stylex catalogue page for Baby Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/baby-pink', 1, 'Stylex catalogue page for Baby Pink.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/berry', 1, 'Stylex catalogue page for Berry.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-berry'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/black', 1, 'Stylex catalogue page for Black.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-black'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/blush', 1, 'Stylex catalogue page for Blush.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-blush'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-bronze-gold', 1, 'Stylex catalogue page for Chrome Bronze Gold.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-bronze-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/burnt-orange', 1, 'Stylex catalogue page for Burnt Orange.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-burnt-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/caribbean-blue', 1, 'Stylex catalogue page for Caribbean Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-caribbean-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-blue', 1, 'Stylex catalogue page for Chrome Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-champagne', 1, 'Stylex catalogue page for Chrome Champagne.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-champagne'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-green', 1, 'Stylex catalogue page for Chrome Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-gold-yellow', 1, 'Stylex catalogue page for Chrome Gold Yellow.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-gold-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-purple', 1, 'Stylex catalogue page for Chrome Purple.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-rose-gold', 1, 'Stylex catalogue page for Chrome Rose Gold.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-rose-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/chrome-silver', 1, 'Stylex catalogue page for Chrome Silver.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-silver'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/coffee', 1, 'Stylex catalogue page for Coffee.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-coffee'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/dark-blue', 1, 'Stylex catalogue page for Dark Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-dark-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/golden-rod-yellow', 1, 'Stylex catalogue page for Golden Rod Yellow.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-golden-rod-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/fashion-red', 1, 'Stylex catalogue page for Fashion Red.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-fashion-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/grey', 1, 'Stylex catalogue page for Grey.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-grey'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/hot-purple', 1, 'Stylex catalogue page for Hot Purple.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hot-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/hunter-green', 1, 'Stylex catalogue page for Hunter Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hunter-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/lavender', 1, 'Stylex catalogue page for Lavender.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/light-blue', 1, 'Stylex catalogue page for Light Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-light-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/lime-green', 1, 'Stylex catalogue page for Lime Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lime-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/matcha-green', 1, 'Stylex catalogue page for Matcha Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-matcha-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/mid-blue', 1, 'Stylex catalogue page for Mid Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mid-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/mint-green', 1, 'Stylex catalogue page for Mint Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mint-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/navy', 1, 'Stylex catalogue page for Navy.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-navy'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/orange', 1, 'Stylex catalogue page for Orange.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-dusk', 1, 'Stylex catalogue page for Pastel Dusk Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-dusk-cream', 1, 'Stylex catalogue page for Pastel Dusk Cream.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-cream'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-dusk-green', 1, 'Stylex catalogue page for Pastel Dusk Laurel Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-laurel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-dusk-lavender', 1, 'Stylex catalogue page for Pastel Dusk Lavender.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-dusk-1', 1, 'Stylex catalogue page for Pastel Dusk Rose.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-rose'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-blue', 1, 'Stylex catalogue page for Pastel Blue.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-green', 1, 'Stylex catalogue page for Pastel Green.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-lilac', 1, 'Stylex catalogue page for Pastel Lilac.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-pink', 1, 'Stylex catalogue page for Pastel Pink.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-light-yellow-1', 1, 'Stylex catalogue page for Pastel Light Yellow.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-light-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pastel-yellow', 1, 'Stylex catalogue page for Pastel Yellow.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/pearl-white', 1, 'Stylex catalogue page for Pearl White.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pearl-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/red', 1, 'Stylex catalogue page for Red.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/rose-pink', 1, 'Stylex catalogue page for Rose Pink.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rose-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/rosewood', 1, 'Stylex catalogue page for Rosewood.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rosewood'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/spring-lilac', 1, 'Stylex catalogue page for Spring Lilac.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-spring-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/white', 1, 'Stylex catalogue page for White.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/white-sand', 1, 'Stylex catalogue page for White Sand.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white-sand'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Stylex Balloons', 'https://stylexballoons.com.au/collections/yellow', 1, 'Stylex catalogue page for Yellow.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Stylex Balloons');

-- Hayden Agencies + Online Party Supplies as fallbacks (URLs left NULL).
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-avocado-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-avocado-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-berry'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-berry'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-black'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-black'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-blush'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-blush'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-bronze-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-bronze-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-burnt-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-burnt-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-caribbean-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-caribbean-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-champagne'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-champagne'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-gold-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-gold-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-rose-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-rose-gold'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-silver'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-silver'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-coffee'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-coffee'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-dark-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-dark-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-golden-rod-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-golden-rod-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-fashion-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-fashion-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-grey'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-grey'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hot-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hot-purple'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hunter-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hunter-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-light-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-light-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lime-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lime-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-matcha-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-matcha-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mid-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mid-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mint-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mint-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-navy'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-navy'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-orange'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-cream'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-cream'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-laurel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-laurel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-lavender'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-rose'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-rose'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-blue'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-green'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-light-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-light-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pearl-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pearl-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-red'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rose-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rose-pink'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rosewood'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rosewood'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-spring-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-spring-lilac'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white-sand'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white-sand'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Hayden Agencies', NULL, 0, 'Backup for latex when Stylex is out.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Hayden Agencies');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
  SELECT id, 'Online Party Supplies', NULL, 0, 'Different balloons, tassels and Orbz.'
  FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-yellow'
  AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Online Party Supplies');