-- 011_ops_foil_letters_numbers.sql
-- Generated by _inbox/generate_ops_foil_migration.py.
--
-- For each foil letter SKU (foil-topper-letter-a..z) we add one OPS
-- supplier source per colour Online Party Supplies stocks. The OPS URL
-- opens that colour's product page where Jade picks the specific letter
-- from a dropdown. Same shape for foil number SKUs (foil-topper-number-0..9).
--
-- We also set photo_url on each letter / number SKU to the most-common-
-- colour's product image (gold for letters, black for numbers) so the Stock
-- row carries a thumbnail.
--
-- Idempotent: NOT EXISTS guards on every supplier source insert.

-- Photo for letter SKUs — uses the gold colour's product image as a sample.
UPDATE inventory_items
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-gold-foil-alphabet-letter-a-z-shaped-foil-balloon-party-decorations_600x.webp', updated_at = datetime('now')
WHERE sku LIKE 'foil-topper-letter-%' AND photo_url IS NULL;

-- Photo for number SKUs.
UPDATE inventory_items
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
WHERE sku LIKE 'foil-topper-number-%' AND photo_url IS NULL;

-- Letter colours from OPS — one supplier source per colour, per letter.
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Gold', 'https://onlinepartysupplies.com.au/products/16inch-40cm-gold-alphabet-letter-foil-balloon-birthday-party-decor', 0, 'OPS 16-inch foil letters in Gold. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Gold');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Rose Gold', 'https://onlinepartysupplies.com.au/products/16-inch-rose-gold-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Rose Gold. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Rose Gold');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Silver', 'https://onlinepartysupplies.com.au/products/16-inch-silver-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Silver. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Silver');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Black', 'https://onlinepartysupplies.com.au/products/16-inch-black-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Black. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Black');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Red', 'https://onlinepartysupplies.com.au/products/16-inch-red-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Red. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Red');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Blue', 'https://onlinepartysupplies.com.au/products/16in-blue-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Blue. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Blue');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Green', 'https://onlinepartysupplies.com.au/products/16-inch-green-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Green. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Green');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Orange', 'https://onlinepartysupplies.com.au/products/16in-orange-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Orange. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Orange');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Purple', 'https://onlinepartysupplies.com.au/products/16-inch-purple-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Purple. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Purple');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Hot Pink', 'https://onlinepartysupplies.com.au/products/16-inch-hot-pink-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Hot Pink. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Hot Pink');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Matte Caramel', 'https://onlinepartysupplies.com.au/products/16inch-matte-caramel-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Matte Caramel. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Matte Caramel');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Matte Cream', 'https://onlinepartysupplies.com.au/products/16inch-cream-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Matte Cream. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Matte Cream');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Rainbow', 'https://onlinepartysupplies.com.au/products/16-inch-gradient-rainbow-a-z-alphabet-letter-foil-balloon', 0, 'OPS 16-inch foil letters in Rainbow. Choose the letter from the dropdown on the product page.'
FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Rainbow');

-- Number colours from OPS — same shape per digit.
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Black', 'https://onlinepartysupplies.com.au/products/16-inch-black-number-0-9-foil-balloon', 0, 'OPS 16-inch foil numbers in Black. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Black');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Silver', 'https://onlinepartysupplies.com.au/products/16in-silver-0-9-number-foil-balloon', 0, 'OPS 16-inch foil numbers in Silver. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Silver');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Red', 'https://onlinepartysupplies.com.au/products/16in-red-0-9-number-foil-balloon', 0, 'OPS 16-inch foil numbers in Red. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Red');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Blue', 'https://onlinepartysupplies.com.au/products/16in-blue-0-9-number-foil-balloon', 0, 'OPS 16-inch foil numbers in Blue. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Blue');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Green', 'https://onlinepartysupplies.com.au/products/16-inch-green-number-0-9-foil-balloon', 0, 'OPS 16-inch foil numbers in Green. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Green');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Orange', 'https://onlinepartysupplies.com.au/products/16-inch-orange-0-9-number-foil-balloon', 0, 'OPS 16-inch foil numbers in Orange. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Orange');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Purple', 'https://onlinepartysupplies.com.au/products/16-inch-purple-number-0-9-foil-balloon', 0, 'OPS 16-inch foil numbers in Purple. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Purple');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Hot Pink', 'https://onlinepartysupplies.com.au/products/16in-hot-pink-0-9-number-foil-balloon', 0, 'OPS 16-inch foil numbers in Hot Pink. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Hot Pink');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Matte Caramel', 'https://onlinepartysupplies.com.au/products/16inch-matte-caramel-number-0-9-foil-balloon', 0, 'OPS 16-inch foil numbers in Matte Caramel. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Matte Caramel');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, is_preferred, notes)
SELECT id, 'OPS — Matte Cream', 'https://onlinepartysupplies.com.au/products/16inch-matte-cream-number-0-9-foil-balloon', 0, 'OPS 16-inch foil numbers in Matte Cream. Choose the digit from the dropdown.'
FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Matte Cream');