-- 012_supplier_source_photos.sql
-- Generated by _inbox/generate_supplier_photos_migration.py
--
-- Adds a photo_url column to inventory_supplier_sources and populates
-- it for every OPS letter / number colour source — turning the Reorder
-- dropdown into a visual colour picker.
--
-- The inventory item's primary photo_url stays as-is (gold-letter image
-- on letter SKUs, black-number on number SKUs). The per-source photo is
-- additive — used in the dropdown only.

ALTER TABLE inventory_supplier_sources ADD COLUMN photo_url TEXT;

-- OPS letter colours — one UPDATE per colour, scoped to that supplier_name
-- pattern. Idempotent because re-applying a UPDATE with the same value is a
-- no-op.
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-gold-foil-alphabet-letter-a-z-shaped-foil-balloon-party-decorations_600x.webp', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Gold'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-rose-gold-a-z-alphabet-letters-foil-balloons-party-decorations-1_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Rose Gold'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Silver'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Black'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-red-letters-alphabet-a-z-foil-balloons-party-decorations-1_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Red'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Blue'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Green'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-orange-letter-alphabet-foil-balloon-birthday-wedding-baby-shower-party-decorations_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Orange'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Purple'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Hot Pink'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-matte-caramel-letter-a-to-z-air-filled-foil-balloon-party-decorations_600x.webp', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Caramel'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-matte-cream-letter-air-filled-foil-balloon-party-decorations_600x.webp', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Cream'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Rainbow'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');

-- OPS number colours.
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Black'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16inch-air-filled-silver-number-0-9-foil-balloon-birthday-wedding-party-event-decorations_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Silver'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-red-numbers-alphabet-foil-balloons-party-decorations_648e4f03-ba3c-4a61-ae3a-9084c26ec0b1_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Red'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-blue-number-foil-balloon-birthday-wedding-baby-shower-party-decorations_2ab28af3-3117-4237-856f-b7217e3a40b0_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Blue'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Green'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-orange-number-0-9-foil-balloon-birthday-wedding-baby-shower-party-decorations_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Orange'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Purple'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-hot-pink-number-foil-balloon-birthday-wedding-baby-shower-party-decorations_31ea50aa-2543-4dfd-b34b-ad6cffbee668_600x.jpg', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Hot Pink'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/16-inch-matte-caramel-number-0-to-9-air-filled-foil-balloon-party-decorations_600x.webp', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Caramel'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET photo_url = 'https://onlinepartysupplies.com.au/cdn/shop/files/online-party-supplies-logo-grey_600x.png', updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Cream'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');

-- Latex Stylex sources — copy the inventory item's photo_url onto the source
-- so the dropdown shows a thumbnail there too. (Inventory item already has
-- the right swatch from migration 010.)
UPDATE inventory_supplier_sources
   SET photo_url = (SELECT photo_url FROM inventory_items WHERE inventory_items.id = inventory_supplier_sources.inventory_item_id),
       updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND photo_url IS NULL
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'balloon-latex-5in-stylex-%');