-- 013_supplier_prices.sql
-- Generated by _inbox/generate_supplier_prices_migration.py
--
-- Pulls the published price from each OPS letter + number colour page
-- (og:price:amount meta tag) and UPDATEs unit_price_cents on every
-- matching supplier_source row. Re-runnable: same SQL produces same
-- result, no duplicates created.

-- Letter colours
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Gold'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 219, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Rose Gold'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Silver'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Black'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Red'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Blue'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Green'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Orange'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Purple'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Hot Pink'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Caramel'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Cream'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Rainbow'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-letter-%' AND sku != 'foil-topper-letter');

-- Number colours
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Black'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Silver'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 199, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Red'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 199, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Blue'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Green'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Orange'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Purple'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Hot Pink'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Caramel'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 239, updated_at = datetime('now')
 WHERE supplier_name = 'OPS — Matte Cream'
   AND inventory_item_id IN (SELECT id FROM inventory_items WHERE sku LIKE 'foil-topper-number-%' AND sku != 'foil-topper-number');