-- 014_stylex_latex_prices.sql
-- Generated by _inbox/generate_stylex_prices_migration.py
--
-- Pulls the 5-inch latex price from each Stylex colour's products.json
-- (Shopify exposes that endpoint per collection) and UPDATEs
-- unit_price_cents on the matching Stylex Balloons supplier source row.
--
-- Re-running this migration is a no-op (UPDATEs are idempotent).

UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-avocado-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-baby-pink');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-berry');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-black');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-blush');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-bronze-gold');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-burnt-orange');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-caribbean-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-champagne');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-purple');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-rose-gold');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 550, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-chrome-silver');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-coffee');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-dark-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-golden-rod-yellow');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-fashion-red');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-grey');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hot-purple');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-hunter-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lavender');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-light-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-lime-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-matcha-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mid-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-mint-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-navy');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-orange');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-cream');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-laurel-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-lavender');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-dusk-rose');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-blue');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-green');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-lilac');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-pink');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-light-yellow');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pastel-yellow');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 520, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-pearl-white');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-red');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rose-pink');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-rosewood');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-spring-lilac');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-white-sand');
UPDATE inventory_supplier_sources
   SET unit_price_cents = 490, updated_at = datetime('now')
 WHERE supplier_name = 'Stylex Balloons'
   AND inventory_item_id = (SELECT id FROM inventory_items WHERE sku = 'balloon-latex-5in-stylex-yellow');