-- 015_misc_supplier_sources.sql
-- Generated by _inbox/generate_misc_supplier_sources.py
--
-- Adds supplier sources for items that previously had no specific
-- product URL. Each row brings: clickable URL, real price, real
-- product image. Idempotent via NOT EXISTS guards.

INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — 24" Transparent Latex', 'https://onlinepartysupplies.com.au/products/24-inch-jumbo-round-transparent-latex-balloon', 299, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/24in-transparent-clear-latex-balloon-birthday-wedding-hen-bridal-baby-shower-party-decorations.webp?v=1759381385', 'OPS / Koch listing for 24-inch Jumbo Round Transparent Latex Balloon'
FROM inventory_items WHERE sku = 'balloon-bubble-24in'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — 24" Transparent Latex');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Multi-colour curling ribbon', 'https://onlinepartysupplies.com.au/products/5mm-10m-multi-colour-curling-ribbon-roll', 80, 1, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/products/5mm-10m-purple-balloon-curling-ribbon-roll-gift-wrapping-birthday-wedding-baby-shower-event-party-decorations_936878c4-16bf-44a7-817c-a81e7e6e86a6.jpg?v=1600684124', 'OPS / Koch listing for Curling Ribbon Roll 5mm x 10m - Multi Colours'
FROM inventory_items WHERE sku = 'ribbon-curled-roll'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Multi-colour curling ribbon');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Metallic gold curling ribbon', 'https://onlinepartysupplies.com.au/products/metallic-gold-foil-curling-ribbon-roll-5mm-10m', 99, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/products/5mm-10m-metallic-gold-foil-balloon-curling-ribbon-roll-gift-wrapping-packaging-birthday-wedding-baby-shower-event-party-decorations.jpg?v=1659497935', 'OPS / Koch listing for Metallic Gold Foil Curling Ribbon Roll - 5mm*10m'
FROM inventory_items WHERE sku = 'ribbon-curled-roll'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Metallic gold curling ribbon');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Metallic rose gold curling ribbon', 'https://onlinepartysupplies.com.au/products/metallic-rose-gold-foil-curling-ribbon-roll-5mm-10m', 99, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/products/5mm-10m-metallic-rose-gold-foil-balloon-curling-ribbon-roll-gift-wrapping-packaging-birthday-wedding-baby-shower-event-party-decorations.jpg?v=1659497981', 'OPS / Koch listing for Metallic Rose Gold Foil Curling Ribbon Roll - 5mm*10m'
FROM inventory_items WHERE sku = 'ribbon-curled-roll'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Metallic rose gold curling ribbon');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Cherry satin ribbon spool', 'https://onlinepartysupplies.com.au/products/20mm-x-9m-cherry-satin-ribbon-spool', 699, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/products/20mm-9m-cherry-Christmas-satin-ribbon-spool-gift-wrapping-tie-bow-craft-supplies.jpg?v=1604744201', 'OPS / Koch listing for Cherry Satin Ribbon Spool 10 Yards'
FROM inventory_items WHERE sku = 'ribbon-satin-roll'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Cherry satin ribbon spool');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'Koch — Crinkle cut white 150g bag', 'https://www.koch.com.au/products/premium-shredded-paper-filler-crinkle-cut-white-150gram-bag', 450, 1, 'https://cdn.shopify.com/s/files/1/0765/2029/2603/files/PSB150WH.jpg?v=1756981830', 'OPS / Koch listing for Premium Shredded Paper Filler Crinkle Cut White 150gram Bag'
FROM inventory_items WHERE sku = 'shredded-paper-white'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Koch — Crinkle cut white 150g bag');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'Koch — Crinkle cut black 150g bag', 'https://www.koch.com.au/products/premium-shredded-paper-filler-crinkle-cut-black-150gram-bag', 450, 1, 'https://cdn.shopify.com/s/files/1/0765/2029/2603/files/PSB150BK.jpg?v=1756988387', 'OPS / Koch listing for Premium Shredded Paper Filler Crinkle Cut Black 150gram Bag'
FROM inventory_items WHERE sku = 'shredded-paper-black'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'Koch — Crinkle cut black 150g bag');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Metallic gold balloon cube box (A-Z)', 'https://onlinepartysupplies.com.au/products/metallic-gold-balloon-cube-box-with-letter-a-to-z', 699, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/clear-transparent-metallic-gold-balloon-cube-box-letter-a-to-z-wedding-bridal-shower-birthday-baby-shower-party-decorations-photo-backdrops-centrepiece.webp?v=1723528458', 'OPS / Koch listing for Metallic Gold Balloon Cube Box with Letter A to Z'
FROM inventory_items WHERE sku = 'gift-box-medium'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Metallic gold balloon cube box (A-Z)');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Metallic rose gold balloon cube box', 'https://onlinepartysupplies.com.au/products/metallic-rose-gold-balloon-cube-box-with-letter', 699, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/metallic-rose-gold-balloon-cube-box-with-letter-baby-shower-gender-reveal-party-decorations-birthday-cake-smash-photo-backdrops.webp?v=1723186812', 'OPS / Koch listing for Metallic Rose Gold Balloon Cube Box with Letter A to Z'
FROM inventory_items WHERE sku = 'gift-box-medium'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Metallic rose gold balloon cube box');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Handheld balloon confetti pop gun', 'https://onlinepartysupplies.com.au/products/inflatable-handheld-balloon-confetti-pop-gun', 199, 1, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/inflatable-balloon-confetti-pop-gun-popper-party-photo-props-decorations-2.webp?v=1725604918', 'OPS / Koch listing for Inflatable Handheld Balloon Confetti Pop Gun'
FROM inventory_items WHERE sku = 'confetti-pop-handpull'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Handheld balloon confetti pop gun');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Gender reveal popper (pink + gold)', 'https://onlinepartysupplies.com.au/products/party-popper-gender-reveal-pink-gold-confetti-hearts', 1699, 1, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/baby-shower-gender-reveal-pink-gold-confetti-popper.jpg?v=1761197755', 'OPS / Koch listing for Party Popper Gender Reveal – Pink & Gold Confetti Hearts'
FROM inventory_items WHERE sku = 'gender-reveal-popper'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Gender reveal popper (pink + gold)');
INSERT INTO inventory_supplier_sources (inventory_item_id, supplier_name, url, unit_price_cents, is_preferred, photo_url, notes)
SELECT id, 'OPS — Gender reveal popper (blue + gold)', 'https://onlinepartysupplies.com.au/products/party-popper-gender-reveal-blue-gold-confetti-hearts', 1699, 0, 'https://cdn.shopify.com/s/files/1/0037/5763/7701/files/gender-reveal-popper-blue-gold-confetti-burst.jpg?v=1761197149', 'OPS / Koch listing for Party Popper Gender Reveal – Blue & Gold Confetti Hearts'
FROM inventory_items WHERE sku = 'gender-reveal-popper'
AND NOT EXISTS (SELECT 1 FROM inventory_supplier_sources s WHERE s.inventory_item_id = inventory_items.id AND s.supplier_name = 'OPS — Gender reveal popper (blue + gold)');